<?php
/**
 * @version		1.0 ferpa_controleprojetos $
 * @package		ferpa_controleprojetos
 * @copyright	Copyright © 2013 - All rights reserved.
 * @license		GNU/GPL
 * @author		augusto
 * @author mail	augusto.rr.arruda@gmail.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here


?>